# Generated by Django 6.0.3 on 2026-03-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activation", "0002_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
