# Generated by Django 6.0.3 on 2026-03-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activation", "0003_alter_asset_code_alter_asset_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
